---
- hosts: all
  tasks;
    - name: "Install OS dependences."
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - apache2
        - libapache2-mod-php5
        - php5-gd
        - libssh2-php
        - php5-mcrypt
        - mysql-server-5.6
        - python-mysqldb
        - php5-mysql

      - name: 'Cria banco MySQLdb'
        mysql_db: 
          name: wordpress_db
          login_user: root
          state: present

#ansible-playbook provisioning.yml -u vagrant -i hosts --private-key .vagrant/machines/wordpress/virtualbox/private_key
#ansible-playbook -i hosts provisioning.yml