---
- hosts: all
  tasks;
    - name: "Instala o PHP5"
      apt:
        name: php5                 #É um apt-get install php5 -y
        state: latest
      become: yes
    - name: "Instala o Apache2"
    apt:
      name: apache2
      state: latest
    become: yes
    - name: "Instala o modphp"
    apt:
      name: libapache2-mod-php5
      state: latest
    become: yes




#ansible-playbook provisioning.yml -u vagrant -i hosts --private-key .vagrant/machines/wordpress/virtualbox/private_key
