---
- hosts: database
  roles:
    - mysql
  
- hosts: wordpress
  roles:
    - wordpress

#ansible-playbook provisioning.yml -u vagrant -i hosts --private-key .vagrant/machines/wordpress/virtualbox/private_key
#ansible-playbook -i hosts provisioning.yml
#vagrant ssh
