---
- hosts: all
  tasks;
    - name: "Install OS dependences."
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - apache2
        - libapache2-mod-php5
        - php5-gd
        - libssh2-php
        - php5-mcrypt
        - mysql-server-5.6
        - python-mysqldb
        - php5-mysql

      - name: 'Cria banco MySQLdb'
        mysql_db: 
          name: wordpress_db
          login_user: root
          state: present

      - name: 'Cria o usuário do MySQL'
        mysql_user:
          login_user: root 
          name: wordpress_user1
          password: 321654
          priv: 'wordpress_db.*:ALL'
          state: present

      - name: 'Baixa o arquivo de instalação via URL do Wordpress'
        get_url:
          url: 'https://wordpress.org/latest.tar.gz'
          dest: 'C:/Users/user1/Downloads'

      - name: 'Descompacta o wordpress'
        unarchive:
          src: 'C:/Users/user1/Downloads'
          dest: 'C:/Users/user1/Documents'
          remote_src: yes
        become: yes

      - copy:
          src: 'C:/Users/user1/Documents/wordpress/wp-config-sample.php'
          dest: 'C:/Users/user1/Documents/wordpress/wp-config.php'
          remote_src: yes
        become: yes

      - name: 'Configura o wp-config w/ db entries'
        replace:
          path: 'C:/Users/user1/Documents/wordpress/wp-config.php'
          regexp: "{{ item.regex }}"
          replace: "{{ item.value }}"
        with_items:
          - { regex: 'database_name_here', value: 'wordpress_db'}
          - { regex: 'username_here', value: 'wordpress_user'}
          - { regex: 'password_here', value: '321654'}
        become: yes                      

#ansible-playbook provisioning.yml -u vagrant -i hosts --private-key .vagrant/machines/wordpress/virtualbox/private_key
#ansible-playbook -i hosts provisioning.yml
#vagrant ssh